### ISSUE TITLE
Installing Ansible on vagrant install 

### ISSUE THREAD

**Issue by jlynch2121** [MI-DPLA/combine-playbook#31]
I have been testing Combine on Windows 10 after using the Vagrant-based install. Combine was working like a charm until very recently when IT upgraded my workstation’s OS to a new version of Windows 10, version 10.0.18362.

This has required me to re-build the system in the virtual environment, like originally (following the instructions on the Combine playbook repository) but unfortunately, the build process appears to get stuck at installing Ansible, which, even after up to 8 hrs of waiting for it to do its thing, never seems to complete.

I understand that Ansible can take some time to install and took a few hours when I originally built the system. However, it did not take more than 8 hrs and I believe something is now broken possibly due to the Windows version update. Thanks in advance for any advice. System and environment info is below.

[Terminal output](https://uofi.box.com/s/f26rrdkzmc21449h6zkad2z6vxmm7cb8)

**OS**: Windows 10.0.18362
**Vagrant** version: 2.2.6
**VirtualBox** version: 6.0.14 r133895 (Qt5.6.2)

**Comment by estelendur** [comment]
At this point, we recommend switching to [the docker project](https://github.com/MI-DPLA/combine-docker) if possible. We aren't able to effectively support multiple deployment methodologies, unfortunately.
